const {chromium}=require('C:/Users/chaya/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {pathToFileURL}=require('url');
const path=require('path');
const fs=require('fs');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 const page=await browser.newPage({viewport:{width:1440,height:1050},deviceScaleFactor:1});
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(path.resolve('dist/index.html')).href);
 await page.locator('#station-table tr').first().waitFor();
 const assert=(x,m)=>{if(!x)throw Error(m)};
 assert(await page.locator('#station-table tr').count()===85,'85 rows');
 for(const [cut,total,b] of [[70,29,9],[60,37,17],[50,55,35],[40,71,51]]){
  await page.locator(`[data-cutoff="${cut}"]`).click();
  assert(await page.locator('#selected-total').textContent()===String(total),'scenario total '+cut);
  assert(await page.locator('#selected-b').textContent()==='B '+b,'scenario B '+cut);
  await page.selectOption('#filter-class','selected');
  assert(await page.locator('#station-table tr').count()===total,'selected list '+cut);
 }
 await page.selectOption('#filter-class','A');
 assert(await page.locator('#station-table tr').count()===20,'A count');
 await page.selectOption('#filter-province','ชัยนาท');
 assert(await page.locator('#station-table').textContent().then(s=>s.includes('สำนักงานเทศบาลตำบลชัยนาท')),'new Chainat A');
 await page.locator('#station-table [data-station]').click();
 assert(await page.locator('#detail').evaluate(e=>e.open),'dialog open');
 assert((await page.locator('#detail-body').textContent()).includes('35.41'),'score');
 await page.keyboard.press('Escape');
 await page.selectOption('#filter-class','C'); await page.selectOption('#filter-province','all');
 assert(await page.locator('#station-table tr').count()===14,'C count');
 assert(await page.locator('#c-list details').count()===14,'C cards');
 await page.locator('#c-list details').first().locator('summary').click();
 assert(await page.locator('#c-list details').first().evaluate(e=>e.open),'C expansion');
 await page.locator('#c-list details').first().locator('summary').click();
 await page.locator('[data-page="5"]').click();
 assert(await page.locator('#pdf-image').evaluate(e=>e.complete&&e.naturalWidth>0),'PDF image load');
 await page.locator('#pdf-next').click();
 assert((await page.locator('#pdf-title').textContent()).includes('6/6'),'PDF navigation');
 await page.keyboard.press('Escape');
 await page.selectOption('#filter-class','all');
 await page.fill('#search','not-a-station-000');assert((await page.locator('#station-table').textContent()).includes('ไม่พบ'),'empty');
 await page.fill('#search','');await page.evaluate(()=>scrollTo(0,0));
 await page.screenshot({path:'analysis/qa-desktop.png'});
 await page.locator('#method').scrollIntoViewIfNeeded();await page.screenshot({path:'analysis/qa-method.png'});
 await page.locator('#class-c').scrollIntoViewIfNeeded();await page.screenshot({path:'analysis/qa-c.png'});
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'analysis/qa-mobile.png'});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile no body overflow');
 await page.setViewportSize({width:1440,height:1050});await page.evaluate(()=>document.documentElement.style.fontSize='200%');
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'200% no body overflow');
 assert(!errors.length,'browser errors '+errors.join(';'));
 const result={passed:true,scenarios:[29,37,55,71],classes:[20,51,14],stationCount:85,cards:14,sourcePages:6,errors};
 fs.writeFileSync('analysis/qa-results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
