const {chromium}=require('C:/Users/chaya/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'}),page=await browser.newPage({viewport:{width:1500,height:1050}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto('http://127.0.0.1:8765/');await page.waitForFunction(()=>window.stationMap?.markers().size===85);assert.equal(await page.locator('#station-table tr').count(),85);
 await page.selectOption('#map-province','เชียงราย');await page.waitForFunction(()=>window.stationMap.markers().size===5);const coords=await page.evaluate(()=>{const m=window.stationMap.markers().get(40);return m.getLatLng();});assert.equal(coords.lat,19.961848);assert.equal(coords.lng,100.235827);
 await page.selectOption('#map-class','A');assert.equal(await page.locator('.station-marker').count(),1);
 await page.selectOption('#map-class','all');await page.locator('#map').scrollIntoViewIfNeeded();await page.waitForFunction(()=>[...document.querySelectorAll('.leaflet-tile')].some(i=>i.complete&&i.naturalWidth>0));await page.waitForFunction(()=>document.querySelector('#mask-status').textContent.includes('76 จังหวัด'));await page.screenshot({path:'analysis/qa-map.png'});
 await page.evaluate(()=>window.stationMap.openStation(40));await page.locator('#map-gallery .photo-empty').waitFor();assert((await page.locator('#map-detail').textContent()).includes('100.235827'));
 await page.goto('http://127.0.0.1:8765/master.html?station=40');await page.locator('#display-name').waitFor();assert.equal(await page.locator('.master-item').count(),85);const original=await page.locator('#display-name').inputValue();
 await page.locator('#show-differences').click();assert.equal(await page.locator('.master-item').count(),10);await page.locator('#only-differences').uncheck();
 await page.fill('#station-notes','ทดสอบบันทึกและแสดงรูปบนแผนที่');await page.locator('#master-form button[type=submit]').click();await page.getByText('บันทึกข้อมูล Master บนเซิร์ฟเวอร์แล้ว',{exact:true}).waitFor();
 const img=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6L1sAAAAASUVORK5CYII=','base64');
 await page.setInputFiles('#photo-files',[{name:'test-front.png',mimeType:'image/png',buffer:img},{name:'test-side.png',mimeType:'image/png',buffer:img}]);await page.locator('#upload-photos').click();await page.getByText('บันทึก 2 รูปบนเซิร์ฟเวอร์แล้ว เปิดดูจากแผนที่ได้ทันที',{exact:true}).waitFor();assert.equal(await page.locator('#master-gallery img').count(),1);assert((await page.locator('#master-gallery').textContent()).includes('รูป 1 / 2'));
 await page.locator('#master-gallery [data-next]').click();assert((await page.locator('#master-gallery').textContent()).includes('รูป 2 / 2'));await page.locator('#master-gallery [data-prev]').click();
 await page.fill('#photo-caption-input','ภาพทดสอบด้านหน้า');await page.locator('#save-caption').click();await page.getByText('บันทึกคำอธิบายรูปแล้ว',{exact:true}).waitFor();
 await page.reload();await page.locator('#display-name').waitFor();assert.equal(await page.locator('#display-name').inputValue(),original);assert.equal(await page.locator('#station-notes').inputValue(),'ทดสอบบันทึกและแสดงรูปบนแผนที่');assert((await page.locator('#master-gallery').textContent()).includes('รูป 1 / 2'));
 await page.screenshot({path:'analysis/qa-master.png'});
 await page.goto('http://127.0.0.1:8765/index.html?station=40#map');await page.locator('#map-gallery img').waitFor();assert.equal(await page.locator('#map-gallery img').count(),1);assert((await page.locator('#map-gallery').textContent()).includes('ภาพทดสอบด้านหน้า'));await page.locator('#map-gallery [data-next]').click();assert((await page.locator('#map-gallery').textContent()).includes('รูป 2 / 2'));
 // Remove only this test's uploaded fixture data from local preview storage.
 await page.evaluate(async()=>{const s=await fetch('/api/stations/40').then(r=>r.json());for(const p of s.photos)if(p.filename.startsWith('test-'))await fetch('/api/photos/'+p.id,{method:'DELETE'});await fetch('/api/stations/40',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({displayName:s.displayName,notes:'',revision:s.revision})});});
 await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:8765/master.html?station=40');await page.locator('#display-name').waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'analysis/qa-master-mobile.png'});
 await page.goto('http://127.0.0.1:8765/#map');await page.waitForFunction(()=>window.stationMap?.markers().size===85);await page.locator('#map').scrollIntoViewIfNeeded();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'analysis/qa-map-mobile.png'});
 assert.deepEqual(errors,[]);fs.writeFileSync('analysis/qa-map-master.json',JSON.stringify({passed:true,markers:85,coordinateDifferences:10,photos:2,reloadPersistence:true,carousel:true,originalCoordinatesPreserved:true,mobile:true,errors},null,2));console.log('PASS: 85 map points, province/class filtering, Excel coordinates, 85 master records, 10 coordinate flags, save, multiple photos, reload, captions, map carousel, mobile, zero JS errors.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
