import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const root = '.pages-dist';
const files = await fs.readdir(root,{recursive:true});
for (const f of files) assert(!/(^|[/\\])(server|\.openai|\.local-data|\.wrangler|node_modules|\.env)([/\\]|$)|\.(sqlite|db)$/i.test(f),f);
for (const file of ['index.html','master.html','common.js','pages-api.js','map.js','text-editor.js','stations.json','sources/site-candidate.pdf','sources/station-classification.xlsx','.nojekyll']) await fs.access(root+'/'+file);
const data = JSON.parse(await fs.readFile(root+'/stations.json','utf8'));
assert.equal(data.stations.length,85);
assert.equal(data.stations.filter(s=>s.class==='A').length,20);
const common = await fs.readFile(root+'/common.js','utf8');
assert(common.includes("export {api} from './pages-api.js?v=20260924b'"));
assert(!common.includes('fetch(path'));
assert(common.includes('station-image-viewer'));
assert(common.includes('เปิดรูปเต็ม'));
const html = await fs.readFile(root+'/index.html','utf8');
assert(html.includes('href="master.html"'));
assert(!html.includes('ไม่ซิงก์มายังหน้านี้'));
assert(html.includes('text-editor.js'));
assert(html.includes('id="filter-b-cutoff"'));
assert(!html.includes('<option value="selected">A+B ตามเกณฑ์ที่เลือก</option>'));
const map = await fs.readFile(root+'/map.js','utf8');
assert(map.includes('href="master.html?station='));
assert(map.includes('คะแนนช่องว่างโครงข่าย (Network Gap)'));
assert(map.includes('ELEV_COMPLEMENTARITY_SCORE'));
const api = await fs.readFile(root+'/pages-api.js','utf8');
assert(api.includes('indexedDB.open'));
assert(api.includes("storage:'this-browser'"));
const editor = await fs.readFile(root+'/text-editor.js','utf8');
assert(editor.includes('✎ แก้คำ'));
assert(editor.includes('localStorage'));
console.log('PASS: Pages allowlist, 85 stations, 20 Class A, public Master storage and local photo attachments.');
