import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const root = '.pages-dist';
const files = await fs.readdir(root,{recursive:true});
for (const f of files) assert(!/(^|[/\\])(server|\.openai|\.local-data|\.wrangler|node_modules|\.env)([/\\]|$)|\.(sqlite|db)$/i.test(f),f);
for (const file of ['index.html','master.html','common.js','pages-api.js','map.js','text-editor.js','stations.json','sources/site-candidate.pdf','sources/station-classification.xlsx','.nojekyll']) await fs.access(root+'/'+file);
const data = JSON.parse(await fs.readFile(root+'/stations.json','utf8'));
assert.equal(data.stations.length,85);
assert.equal(data.stations.filter(s=>s.class==='A').length,20);
const common = await fs.readFile(root+'/common.js','utf8');
assert(common.includes("export {api} from './pages-api.js?v=20260924c'"));
assert(!common.includes('fetch(path'));
assert(common.includes('station-image-viewer'));
assert(common.includes('เปิดรูปเต็ม'));
const html = await fs.readFile(root+'/index.html','utf8');
assert(html.includes('href="master.html"'));
assert(!html.includes('ไม่ซิงก์มายังหน้านี้'));
assert(html.includes('text-editor.js'));
assert(html.includes('id="filter-b-cutoff"'));
assert(html.includes('data-station-sort="class"'));
assert(html.includes('data-station-sort="result"'));
assert(html.includes('data-scenario-sort="remaining"'));
assert(html.includes('function setSort(kind,key)'));
assert(html.includes("document.addEventListener('keydown'"));
assert(!html.includes('<option value="selected">A+B ตามเกณฑ์ที่เลือก</option>'));
assert(html.includes('ส่วนที่เหลือ = 85 − Class A − Class B'));
assert(!html.includes('data-scenario-sort="pendingB"'));
for (const id of ['c-filter-province','c-filter-primary','c-filter-secondary','c-filter-zone']) assert(html.includes(`id="${id}"`));
const map = await fs.readFile(root+'/map.js','utf8');
assert(map.includes('href="master.html?station='));
assert(map.includes("คะแนนช่องว่างโครงข่าย (${parts?.networkKey||'O'})"));
assert(map.includes('คะแนนความต่างระดับความสูง (Q)'));
assert(map.includes('คำนวณจากปัจจัย:'));
assert(map.includes('0.50×${scoreValue(x.network)}'));
assert(map.includes("id:'rainfall'"));
assert(map.includes("fillOpacity:1"));
assert(map.includes("radius:8,color:'#fff',weight:2,opacity:1,fillColor:color"));
assert(map.includes("if(rainfall){const fresh=feature.properties?.class==='every day'"));
assert(map.includes('fill:true,fillColor:color,fillOpacity:1'));
assert(map.includes('คุณภาพต่ำ / ไม่อัปเดตทุกวัน'));
assert(map.includes('layers.set(c.id,layer)'));
assert(map.includes("map.removeLayer(layer);layers.delete(id);el('state-'+id).textContent='ปิด'"));
assert(map.includes("id:'risk'"));
assert(map.includes('Tambon_DDPM_Prov_risk/FeatureServer/0'));
assert(map.includes('ปภ.ส่วนกลาง + ปภ.จังหวัดเห็นตรงกัน'));
assert(map.includes("['1','3'].includes(String(f.properties?.score_1))"));
assert(map.includes('อัปเดตทุกวัน'));
assert(html.includes('c-score-factors'));
assert(html.includes('Score = 0.50(Network Gap) + 0.15(Elevation Difference) + 0.20(Slope) + 0.15(Local Relief)'));
assert(html.includes('N · SLOPE_SCORE'));
assert(html.includes('Q · ELEV_COMPLEMENTARITY_SCORE'));
assert(html.includes('คำนวณจากปัจจัย:'));
assert(html.includes("(0.50×'+scoreText(x.network)+')"));
assert(html.includes('#b-cutoff-filter[hidden]'));
const api = await fs.readFile(root+'/pages-api.js','utf8');
assert(api.includes('indexedDB.open'));
assert(api.includes('navigator.storage?.persist'));
assert(api.includes('exportLocalBackup'));
assert(api.includes('importLocalBackup'));
const master = await fs.readFile(root+'/master.html','utf8');
assert(master.includes('สำรองรูปและ Master'));
assert(master.includes('deploy รุ่นใหม่'));
assert(api.includes("storage:'this-browser'"));
assert(api.includes("Rainfall_data_freq2/FeatureServer/0"));
assert(api.includes("Tambon_DDPM_Prov_risk/FeatureServer/0"));
const editor = await fs.readFile(root+'/text-editor.js','utf8');
assert(editor.includes('✎ แก้คำ'));
assert(editor.includes('localStorage'));
console.log('PASS: Pages allowlist, 85 stations, 20 Class A, public Master storage and local photo attachments.');
