import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const root = '.pages-dist';
const files = await fs.readdir(root,{recursive:true});
for (const f of files) assert(!/(^|[/\\])(server|\.openai|\.local-data|\.wrangler|node_modules|\.env)([/\\]|$)|\.(sqlite|db)$/i.test(f),f);
for (const file of ['index.html','master.html','common.js','pages-api.js','map.js','stations.json','sources/site-candidate.pdf','sources/station-classification.xlsx','.nojekyll']) await fs.access(root+'/'+file);
const data = JSON.parse(await fs.readFile(root+'/stations.json','utf8'));
assert.equal(data.stations.length,85);
assert.equal(data.stations.filter(s=>s.class==='A').length,20);
const common = await fs.readFile(root+'/common.js','utf8');
assert(common.includes("export {api} from './pages-api.js'"));
assert(!common.includes('fetch(path'));
const html = await fs.readFile(root+'/index.html','utf8');
assert(html.includes('ไม่ซิงก์มายังหน้านี้'));
assert(!html.includes('href="master.html"'));
const map = await fs.readFile(root+'/map.js','utf8');
assert(map.includes('https://station-class-decision.chayanrot-ja.chatgpt.site/master.html?station='));
assert(!map.includes('`มีรูปแล้ว'));
console.log('PASS: Pages allowlist, 85 stations, 20 Class A, relative assets, central Master links and explicit read-only storage.');
