import {api,escapeHTML as esc,mountGallery} from './common.js?v=20260924b';
const L=window.L,el=id=>document.getElementById(id),base=JSON.parse(el('report-data').textContent).stations;
let stations=base.map(s=>({...s,displayName:s.masterName||s.name,photoCount:null})),cutoff=40,selectedId=null,selectionToken=0,markers=new Map(),loadToken=0;
const config=[{id:'province',name:'ขอบเขตจังหวัด + ชื่อจังหวัด',color:'#fff2a0',min:0,checked:true},{id:'district',name:'ขอบเขตอำเภอ',color:'#dec79f',min:0,checked:true},{id:'subdistrict',name:'ขอบเขตตำบล',color:'#d4dce7',min:10,checked:false},{id:'major',name:'เส้นน้ำหลัก',color:'#25caff',min:8,checked:true},{id:'minor',name:'เส้นน้ำรอง',color:'#90e5ff',min:10,checked:false},{id:'rainfall',name:'สถานีฝนอื่น (เขียว/แดง)',color:'#1c9b51',min:8,checked:false}];
const urls={major:'04Hydro_MajorStream/FeatureServer/0',minor:'04Hydro_MinorStream/FeatureServer/0',province:'Map116/DPM_TH_Province_DSS/FeatureServer/1',district:'Map116/DPM_TH_Amphoe_DSS/FeatureServer/1',subdistrict:'Map116/DPM_TH_Tambon_DSS/FeatureServer/1',mask:'Hosted/Province_Gray/FeatureServer/0',rainfall:'Hosted/Rainfall_data_freq2/FeatureServer/0'};
const map=L.map('station-map',{zoomControl:true,preferCanvas:true,minZoom:5,maxZoom:19}).setView([13.2,100.8],6);
map.zoomControl.getContainer().setAttribute('aria-label','ย่อและขยายแผนที่');
map.zoomControl.getContainer().querySelector('.leaflet-control-zoom-in').setAttribute('title','ขยายแผนที่');
map.zoomControl.getContainer().querySelector('.leaflet-control-zoom-out').setAttribute('title','ย่อแผนที่');
map.createPane('hydro');map.getPane('hydro').style.zIndex=410;map.createPane('rainfall');map.getPane('rainfall').style.zIndex=430;map.createPane('boundary');map.getPane('boundary').style.zIndex=420;map.createPane('province-label');map.getPane('province-label').style.zIndex=440;map.getPane('province-label').style.pointerEvents='none';map.createPane('province-mask');map.getPane('province-mask').style.zIndex=450;map.getPane('province-mask').style.pointerEvents='none';
const imagery=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Tiles © Esri — Source: Esri, Maxar, Earthstar Geographics, and the GIS User Community'}).addTo(map);
let tileErrors=0;imagery.on('tileerror',()=>{tileErrors++;el('map-basemap-status').textContent='ภาพดาวเทียมบางส่วนโหลดไม่สำเร็จ';});imagery.on('tileload',()=>{if(tileErrors===0)el('map-basemap-status').textContent='ArcGIS World Imagery';});
const layers=new Map(),pointLayer=L.layerGroup().addTo(map);let maskLayer=null;
el('layer-controls').innerHTML=config.map(c=>`<div class="layer-line"><label><input type="checkbox" data-layer="${c.id}" ${c.checked?'checked':''}><span class="layer-sample" style="background:${c.color}"></span>${c.name}</label><small id="state-${c.id}">รอโหลด</small></div>`).join('');
el('map-sources').innerHTML=config.map(c=>`<a target="_blank" rel="noopener" href="https://gis-portal.disaster.go.th/arcgis/rest/services/${urls[c.id]}">${c.name} ↗</a>`).join('')+'<a target="_blank" rel="noopener" href="https://gis-portal.disaster.go.th/portal/home/item.html?id=6972854493074d108fd7421c09a7ce3b">Province_Gray ↗</a>';
el('map-province').innerHTML+=[...new Set(base.map(s=>s.province))].sort((a,b)=>a.localeCompare(b,'th')).map(p=>`<option>${esc(p)}</option>`).join('');
function filtered(){return stations.filter(s=>(el('map-province').value==='all'||s.province===el('map-province').value)&&(el('map-class').value==='all'||(el('map-class').value==='selected'?(s.class==='A'||s.class==='B'&&s.score>cutoff):s.class===el('map-class').value)));}
function drawPoints(fit=false){pointLayer.clearLayers();markers.clear();const list=filtered();for(const s of list){const color={A:'#2664cf',B:'#007f81',C:'#c98a23'}[s.class],m=L.marker([s.lat,s.lon],{icon:L.divIcon({className:'station-marker'+(s.id===selectedId?' selected':''),html:`<span class="station-dot" style="--dot:${color}"></span>`,iconSize:[18,18],iconAnchor:[9,9]}),title:s.displayName,alt:s.displayName,keyboard:true});m.bindTooltip(document.createTextNode(`${s.displayName} · Class ${s.class}`),{direction:'top',offset:[0,-12]});m.on('click',()=>openStation(s.id));m.addTo(pointLayer);markers.set(s.id,m);}el('map-count').textContent=`${list.length} / 85 จุด`;if(fit&&list.length){map.stop();map.fitBounds(L.latLngBounds(list.map(s=>[s.lat,s.lon])),{padding:[36,36],maxZoom:12,animate:false});}if(selectedId&&!list.some(s=>s.id===selectedId))closeDetail();}
function closeDetail(){selectionToken++;selectedId=null;el('map-detail').innerHTML='<div class="map-empty"><span class="location-symbol">◎</span><h3>เลือกจุดบนแผนที่</h3><p>ดูพิกัด Class และรูปสถานที่</p></div>';drawPoints();}
const scoreValue=v=>Number.isFinite(Number(v))?Number(v).toFixed(2):'ไม่มีข้อมูล';
async function openStation(id){const s=stations.find(s=>s.id===id);if(!s)return;const sc=s.scores||{};selectedId=id;const token=++selectionToken;drawPoints();el('map-detail').innerHTML=`<button class="close-detail" aria-label="ปิดรายละเอียด">×</button><span class="class-badge ${s.class}">Class ${s.class}</span><h3>${esc(s.displayName)}</h3><p>ต.${esc(s.subdistrict)} อ.${esc(s.district)}<br>จ.${esc(s.province)}</p><div class="position">${s.lat}, ${s.lon}<br>พื้นที่สี${esc(s.zone)} · สถานี${esc(s.status)}</div><div class="score-breakdown" aria-label="รายละเอียดคะแนนจาก Excel"><strong>รายละเอียดคะแนนจาก Excel</strong><div><span>คะแนนความเหมาะสมเชิงพื้นที่รวม</span><b>${scoreValue(s.score)} /100</b></div><div><span>คะแนนความลาดชัน (SLOPE_SCORE)</span><b>${scoreValue(sc.N)}</b></div><div><span>คะแนนช่องว่างโครงข่าย (Network Gap)</span><b>${scoreValue(sc.O)}</b></div><div><span>คะแนนความซับซ้อนของภูมิประเทศ (RELIEF_SCORE)</span><b>${scoreValue(sc.P)}</b></div><div><span>คะแนนความต่างระดับความสูง (ELEV_COMPLEMENTARITY_SCORE)</span><b>${scoreValue(sc.Q)}</b></div></div><div id="map-gallery" class="map-gallery"><div class="photo-frame"><div class="photo-empty">กำลังโหลดรูปภาพ…</div></div></div><a class="outline" href="master.html?station=${s.id}">จัดการข้อมูล / แนบรูป ↗</a><p class="note">Excel: ${esc(s.source)} แถว ${s.row} · M–Q</p>`;el('map-detail').querySelector('.close-detail').onclick=closeDetail;
 try{const detail=await api('/api/stations/'+id);if(token!==selectionToken)return;mountGallery(el('map-gallery'),detail.photos);if(detail.notes){const p=document.createElement('p');p.textContent=detail.notes;p.className='note';el('map-detail').append(p);}}
 catch(e){if(token===selectionToken)el('map-gallery').innerHTML=`<div class="notice error-text">${esc(e.message)}<br><button class="outline" id="retry-photos">ลองโหลดรูปใหม่</button></div>`;el('retry-photos')?.addEventListener('click',()=>openStation(id));}
}
async function geo(key,params,signal){let features=[],offset=0;for(let page=0;page<12;page++){const q=new URLSearchParams({...params,offset});const data=await api('/api/gis/'+key+'?'+q,{signal});features.push(...data.features);if(data.nextOffset==null)return {type:'FeatureCollection',features};if(data.nextOffset<=offset)throw Error('บริการส่งข้อมูลซ้ำ กรุณาซูมเข้า');offset=data.nextOffset;}throw Error('ชั้นข้อมูลมีจำนวนมาก กรุณาซูมเข้าเพื่อแสดงให้ครบ');}
let controller;
async function loadLayers(){const token=++loadToken;controller?.abort();controller=new AbortController();const signal=controller.signal,p=el('map-province').value,b=map.getBounds(),zoom=map.getZoom(),params={bbox:[b.getWest(),b.getSouth(),b.getEast(),b.getNorth()].join(','),province:p,tolerance:String(Math.max(0.00001,0.003/2**(zoom-7)))};
 let failures=[];await Promise.all(config.map(async c=>{const state=el('state-'+c.id);state.className='';if(layers.has(c.id)){map.removeLayer(layers.get(c.id));layers.delete(c.id);}const enabled=document.querySelector(`[data-layer="${c.id}"]`).checked;if(!enabled){state.textContent='ปิด';return;}if(zoom<c.min){state.textContent='ซูมเข้าอย่างน้อย '+c.min;return;}state.textContent='กำลังโหลด…';try{const data=await geo(c.id,c.id==='province'?{province:p,tolerance:'0.002'}:params,signal);if(token!==loadToken)return;const rainfall=c.id==='rainfall';const shapes=L.geoJSON(data,{pane:rainfall?'rainfall':(c.id==='major'||c.id==='minor'?'hydro':'boundary'),interactive:rainfall,style:{color:c.color,weight:c.id==='major'?2.4:c.id==='province'?1.8:1,opacity:.85,fill:false},pointToLayer:(feature,latlng)=>{const props=feature.properties||{},fresh=props.class==='every day';return L.circleMarker(latlng,{pane:'rainfall',className:'rainfall-marker',radius:5,color:'#fff',weight:1.4,fillColor:fresh?'#1c9b51':'#d6444f',fillOpacity:.95});},onEachFeature:(feature,featureLayer)=>{if(!rainfall)return;const d=feature.properties||{},fresh=d.class==='every day',raw=d.class||'ไม่มีข้อมูล';featureLayer.bindTooltip(`<strong>${esc(d.station_display_name||d.station_id||'สถานีฝน')}</strong><br><span style="color:${fresh?'#1c9b51':'#d6444f'}">●</span> ${fresh?'เขียว · อัปเดตทุกวัน':'แดง · รอบอัปเดตอื่น'}<br>รอบข้อมูล: ${esc(raw)}<br>จังหวัด: ${esc(d.prov_nam_t||'-')}<br>วันที่ข้อมูล: ${esc(d.data_dt||'-')}`,{sticky:true,direction:'top'});}});let layer=shapes;if(c.id==='province'){const wanted=new Set(p==='all'?base.map(s=>s.province):[p]),labels=L.layerGroup();shapes.eachLayer(featureLayer=>{const props=featureLayer.feature?.properties||{},name=props.PROV_NAM_T||props.prov_nam_t;if(!name||!wanted.has(name)||!featureLayer.getBounds)return;L.marker(featureLayer.getBounds().getCenter(),{pane:'province-label',interactive:false,icon:L.divIcon({className:'province-label',html:`<span>${esc(name)}</span>`,iconSize:null})}).addTo(labels);});layer=L.layerGroup([shapes,labels]);}layer.addTo(map);state.textContent=data.features.length+' รายการ';}catch(e){if(token!==loadToken)return;state.textContent='โหลดไม่สำเร็จ';state.className='layer-error';failures.push(c.name+': '+e.message);}}));if(token!==loadToken)return;el('map-layer-status').textContent=failures.length?failures.join(' · '):'แสดงขอบเขตอำเภอและชื่อจังหวัดแล้ว • เลื่อนหรือซูมแผนที่เพื่ออัปเดตชั้นข้อมูล';el('map-layer-status').classList.toggle('error-text',failures.length>0);}
let maskData,maskPromise;async function loadMask(){if(maskLayer){map.removeLayer(maskLayer);maskLayer=null;}if(!el('map-mask').checked){el('mask-status').textContent='';return;}try{if(!maskData){maskPromise??=Promise.all([geo('mask',{tolerance:'0.002'},undefined),geo('province',{tolerance:'0.002'},undefined)]).then(([gray,prov])=>{const byName=new Map();for(const f of [...prov.features,...gray.features]){const name=f.properties.prov_nam_t||f.properties.PROV_NAM_T;if(name)byName.set(name,{...f,properties:{...f.properties,maskProvince:name}});}return {type:'FeatureCollection',features:[...byName.values()]};});maskData=await maskPromise;}if(!el('map-mask').checked)return;const p=el('map-province').value,keep=new Set(p==='all'?base.map(s=>s.province):[p]);const data={type:'FeatureCollection',features:maskData.features.filter(f=>!keep.has(f.properties.maskProvince))};if(maskLayer)map.removeLayer(maskLayer);maskLayer=L.geoJSON(data,{pane:'province-mask',interactive:false,style:{fillColor:'#293441',fillOpacity:.9,color:'#48515e',weight:.3}}).addTo(map);el('mask-status').textContent=`ซ่อนพื้นที่อื่น ${data.features.length} จังหวัด จากขอบเขตรวม ${maskData.features.length} จังหวัด (Province_Gray + ขอบเขตจังหวัด ปภ.)`;}catch(e){maskPromise=null;el('mask-status').textContent='ชั้นซ่อนจังหวัดโหลดไม่สำเร็จ: '+e.message;}}
let timer;map.on('moveend',()=>{clearTimeout(timer);timer=setTimeout(loadLayers,450);});
el('map-province').onchange=()=>{drawPoints(true);void loadMask();};el('map-class').onchange=()=>drawPoints(true);el('map-mask').onchange=()=>void loadMask();el('map-fit').onclick=()=>drawPoints(true);document.querySelectorAll('[data-layer]').forEach(c=>c.onchange=()=>void loadLayers());
window.addEventListener('report-cutoff',e=>{cutoff=e.detail;if(el('map-class').value==='selected')drawPoints();});
drawPoints(true);void loadLayers();void loadMask();
api('/api/stations').then(data=>{stations=data.stations;drawPoints();el('map-storage-status').textContent=`มีรูปแล้ว ${stations.filter(s=>s.photoCount>0).length} / 85 จุด`;const id=Number(new URL(location.href).searchParams.get('station'));if(id&&markers.has(id)){const s=stations.find(s=>s.id===id);map.setView([s.lat,s.lon],14);void openStation(id);}}).catch(e=>{el('map-storage-status').textContent='แสดงพิกัดต้นฉบับ • ข้อมูลรูปยังไม่พร้อม';el('map-storage-status').title=e.message;});
// Expose the map instance only for browser regression checks, not as a data store.
window.stationMap={map,markers:()=>markers,openStation,filtered};
